//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PDImagem.rc
//
#define IDR_MAINFRAME                   2
#define IDR_PDIMAGTYPE                  3
#define IDD_ABOUTBOX                    100
#define IDD_HISTOGRAMA                  101
#define IDD_DIALOG2                     104
#define IDD_LIMIARMANUAL                104
#define IDB_BITMAP1                     106
#define IDI_ICON1                       108
#define IDC_VERMELHO                    110
#define IDC_VERDE                       111
#define IDC_AZUL                        112
#define IDC_AREA_DESENHO                116
#define IDD_ELEMESTR                    117
#define IDC_HSI                         133
#define IDC_RGB                         134
#define IDC_ESCALA                      135
#define IDC_LIMIAR                      137
#define IDD_OPLOGICA                    138
#define IDD_INFO                        140
#define IDD_DIALOG6                     141
#define IDB_BMPHS                       142
#define IDC_TESTAR                      143
#define IDB_BMPHI                       143
#define IDC_COMBO1                      144
#define IDC_IMAGEMB                     144
#define IDC_MASCARA                     144
#define IDB_BMPSI                       144
#define IDC_IMAGEM                      145
#define IDI_ICON2                       145
#define IDC_IMAGEMR                     148
#define IDC_RADIOCR                     151
#define IDD_DIALOG9                     151
#define IDC_RADIOLH                     152
#define IDD_FATORZOOM                   152
#define IDC_RADIOLV                     153
#define IDD_PR_DISTANCIA                153
#define IDC_RADIOQU                     154
#define IDD_DLG_COOCORRENCIA            154
#define IDC_RADIORB                     155
#define IDC_ITERAR                      157
#define IDD_FATORZOOM_INTERP            157
#define IDC_OK                          158
#define ID_APRIMORANITIDEZCALCULO2      159
#define ID_APRIMORANITIDEZCALCULO3      160
#define IDC_IMAGEMA                     163
#define IDC_OR                          164
#define IDC_AND                         165
#define IDC_XOR                         166
#define IDC_AREATES                     167
#define IDC_NAND                        169
#define IDC_NOR                         170
#define IDC_VISUALIZA                   171
#define IDC_IMAGEMEX                    172
#define IDC_IMAGEM_TESTE                173
#define IDC_TITULO                      174
#define IDC_ALTURA                      175
#define IDC_LARGURA                     176
#define IDC_PLANOS                      177
#define IDC_BPS                         178
#define IDC_CORES                       179
#define IDC_TITULO_TESTE                180
#define IDC_TAMANHO                     181
#define IDC_DISTANCIA                   181
#define IDC_NORMAL                      182
#define IDC_CONDICIONAL                 183
#define IDC_TXITERAR                    184
#define IDC_TXOPERACAO                  185
#define IDC_TXMASCARA                   186
#define IDC_PROJECAO                    188
#define IDC_HS                          195
#define IDC_HI                          196
#define IDC_SI                          197
#define IDC_CY                          200
#define IDC_CX                          201
#define IDC_AREAVISUAL                  219
#define IDC_VISUAL                      220
#define IDC_X1                          224
#define IDC_X2                          225
#define IDC_X3                          226
#define IDC_AMOSTRA                     229
#define IDC_HME                         230
#define IDC_HMA                         231
#define IDC_SME                         232
#define IDC_SMA                         233
#define IDC_IME                         234
#define IDC_IMA                         235
#define IDC_AREAREL                     239
#define IDC_IMAGEMRA                    240
#define IDC_IMAGEMRB                    241
#define IDC_VISUALREL                   242
#define IDC_MANTER_A                    243
#define IDC_MCO                         244
#define IDC_CSE                         245
#define IDC_MUC                         246
#define IDC_MUCMCO                      248
#define IDC_MUCCSE                      249
#define IDC_STATIC1                     252
#define IDC_STATIC2                     253
#define IDC_STATIC4                     254
#define IDC_APLICAR                     256
#define IDC_INCREMENTO                  257
#define IDC_ZOOML                       258
#define IDC_ZOOMH                       259
#define IDC_TITULO_PADRAO               261
#define IDC_IMAGEM_PADRAO               262
#define IDC_ED00                        265
#define ID_MOSTRA                       266
#define IDC_ED01                        267
#define IDC_EDIT1                       267
#define IDC_EDIT_FAT_INTERP             267
#define IDC_ED10                        268
#define IDC_ED11                        269
#define ID_OK                           269
#define ID_CANCEL						270
#define IDC_CRUZ                        900
#define IDC_TRES                        901
#define IDC_LINHAH                      902
#define IDC_LINHAV                      903
#define IDC_ROMBUS                      904
#define ID_GOODBYE                      999
#define ID_IMAGEM_HISTOGRAMA            32768
#define ID_IMAGEM_CANAL_DIVIDEHSI       32771
#define ID_IMAGEM_CANAL_DIDIVERGB       32772
#define ID_IMAGEM_CANAL_HISTO           32772
#define ID_IMAGEM_EQUALIZACAO           32774
#define ID_IMAGEM_LIMIARIZACAO_OTSU     32776
#define ID_IMAGEM_LIMIARIZACAO_MEDIA    32777
#define ID_IMAGEM_LIMIARIZACAO_KITTLER  32778
#define ID_IMAGEM_LIMIARIZACAO_ENTROPIA 32779
#define ID_IMAGEM_LIMIARIZACAO_ANISOTROPIA 32780
#define ID_IMAGEM_INVERTE               32781
#define ID_IMAGEM_LIMIARIZACAO_MANUAL   32782
#define ID_MORFOLOGIA_BINARIA_EROSAO    32785
#define ID_MORFOLOGIA_BINARIA_DILATACAO 32786
#define ID_MORFOLOGIA_BINARIA_FECHAMENTO 32787
#define ID_MORFOLOGIA_BINARIA_ABERTURA  32793
#define ID_MORFOLOGIA_BINARIA_BORDAS_EROSAO 32795
#define ID_MORFOLOGIA_BINARIA_BORDAS_DILATACAO 32798
#define ID_MORFOLOGIA_BINARIA_BORDAS_DILERO 32799
#define ID_MORFOLOGIA_BINARIA_ESQUELETIZACAO 32800
#define ID_OPERACOES_LOGICAS            32804
#define ID_OPERACOES_ARITMETICAS        32805
#define ID_MORFOLOGIA_BINARIA_ULTIMAEROSAO 32806
#define ID_IMAGEM_CANAL_SEGMENTA        32807
#define ID_IMAGEM_CANAL_SEGMENTAHSI     32808
#define ID_OPERACOES_RELACAO            32810
#define ID_OPERACOES_FECHA              32811
#define ID_OPERACOES_SEPARA             32812
#define ID_IMAGEM_INCREMENTO            32813
#define ID_IMAGEM_PERFILSUPERIOR        32820
#define ID_IMAGEM_PERFILINFERIOR        32821
#define ID_IMAGEM_ENQUADRAMENTO         32822
#define ID_IMAGEM_EPSI                  32823
#define ID_IMAGEM_ZOOM                  32824
#define ID_IMAGEM_AFINAMENTO            32826
#define ID_ZHANG                        32828
#define ID_IMAGEM_TONSDECINZA           32844
#define ID_LINE_MASKS_VERTICAL          32846
#define ID_LINE_MASKS_HORIZONTAL        32847
#define ID_LINE_MASKS_MAIS_45           32848
#define ID_LINE_MASKS_MENOS_45          32849
#define ID_PEDRO_POINTDETECTION         32850
#define ID_PEDRO_PREWITT                32851
#define ID_PEDRO_TONSDECINZA            32853
#define ID_PEDRO_TONSDECINZA_NTSC       32854
#define ID_PEDRO_NON                    32855
#define ID_PEDRO_LAPLACIANMASK          32856
#define ID_PEDRO_HIGHBOOST              32857
#define ID_PEDRO_LINEMASKS_TOTAL        32858
#define ID_PEDRO_MATRIZ                 32859
#define ID_PEDRO_RGB_NORMALIZAO         32861
#define ID_PEDRO_RGB_TSL_T              32862
#define ID_PEDRO_RGB_TSL_S              32863
#define ID_PEDRO_RGB_TSL_L              32864
#define ID_PEDRO_RGB_GERAHISTOGRAMA     32865
#define ID_PEDRO_RGB_GERAHISTOGRAMATSL  32866
#define ID_PEDRO_RGB_CIELUV_L           32867
#define ID_PEDRO_RGB_CIELUV_U           32868
#define ID_PEDRO_RGB_CIELUV_V           32869
#define ID_XYZ_EXTRAIR_X                32871
#define ID_XYZ_EXTRAIR_Y                32872
#define ID_XYZ_EXTRAIR_Z                32873
#define ID_XYZ_CONVERTE                 32874
#define ID_CIELUV_EXTRAIR_L             32876
#define ID_CIELUV_EXTRAIR_U             32877
#define ID_CIELUV_EXTRAIR_V             32878
#define ID_CIELUV_CONVERTE              32879
#define ID_HSV_EXTRAIR_CANAIS           32880
#define ID_HSV_EXTRAIR_CANAIS_CARDANI   32881
#define ID_ZOOM_TRI32882                32882
#define ID_Menu                         32883
#define ID_ZOOM_TRIANGULO               32884
#define ID_ZOOM_BELL                    32885
#define ID_ZOOM_HERMITTE                32886
#define ID_ZOOM_MITCHELL                32887
#define ID_ZOOM_CUBIC                   32888
#define ID_PROCESSAMENTOEMCOR_HSI       32889
#define ID_ZOOM_NOVOM                   32890
#define ID_PROCESSAMENTOEMCOR_YCRCB     32891
#define ID_PROCESSAMENTOEMCOR_YIQ       32892
#define ID_HSV_CONVERS32893             32893
#define ID_APRIMORANITIDEZCALCULO1      32893
#define ID_HSI_CONVERS32894             32894
#define ID_ESPACOSDECOR_HSV_EXTRAIR_CANAIS 32895
#define ID_XYZ_CONVERS32896             32896
#define ID_YCRCB_CONVERS32897           32897
#define ID_YIQ_CONVERS32898             32898
#define ID_YIQ_EQUALIZA32899            32899
#define ID_YIQ_APRIMORAMENTODENITIDEZ   32900
#define ID_ESPAOSDECOR_HSI_CONVERSORGBPARAHSIHSIPARARGB 32901
#define ID_ESPACOSDECOR_XYZ             32902
#define ID_ESPAOSDECOR_YCRCB_CONVERTER_RGB_YCRCB 32903
#define ID_ESPACOSDECOR_YIQ             32904
#define ID_IMAGEM_EQUALIZACAO_YIQ       32905
#define ID_YCRCB_C32906                 32906
#define ID_YCRCB_C32907                 32907
#define ID_YCRCB_C32908                 32908
#define ID_YCRCB_APRIMORAMENTODENITIDEZ 32909
#define ID_APRIMORAMENTODENITIDEZ_C32910 32910
#define ID_APRIMORAMENTODENITIDEZ_C     32911
#define ID_APRIMORAMENTODENITIDEZ_C32912 32912
#define ID_YCRCB_EQUALIZA32913          32913
#define ID_YCRCBEQUALIZACAO             32914

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32915
#define _APS_NEXT_CONTROL_VALUE         268
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
